name: road_sentinel
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  flutter_native_splash: 2.3.1
  flutter_svg: 2.0.4
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: 4.0.3
  intl: 0.18.0
  json_path: 0.4.1
  page_transition: 2.0.4
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  provider: 6.0.4
  shared_preferences: 2.0.15
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  sqflite: 2.2.6
  timeago: 3.2.2
  universal_io: 2.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  xml: 6.3.0
  is_first_run: ^1.0.0
  http: ^0.13.0
  camera: ^0.10.5+3
  permission_handler: ^10.4.3
  location: ^5.0.3
  http_parser: ^4.0.2
  image: ^4.0.17
  wakelock: ^0.6.2
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

